all:
	g++ -o editor.fpp editor.fpp.cpp ../libf++.cpp -I ../ -lncurses -std=c++17 -O2
	g++ -o editor.stl editor.stl.cpp -lncurses -std=c++17 -O2
	g++ -o pass.fpp pass.fpp.cpp ../libf++.cpp -I ../ -std=c++17 -O2
	g++ -o pass.stl pass.stl.cpp -std=c++17 -O2
	g++ -o pass.stl.broken pass.stl.broken.cpp -std=c++17 -O2

